CREATE TABLE COLLECTION
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as INDEPENDENT_AUTHORITY_ID,
    (SELECT COLLECTION_TYPE_CODE FROM COLLECTION_TYPE_CODE ctc
    WHERE TO_DATE(sld_student.REPORT_DATE,'YYYYMMDD')
    BETWEEN TO_DATE(EXTRACT(YEAR FROM TO_DATE(sld_student.REPORT_DATE,'YYYYMMDD')) || LPAD(EXTRACT(MONTH FROM ctc.OPEN_DATE),2,'0') || '01','YYYYMMDD')
    AND TO_DATE(EXTRACT(YEAR FROM TO_DATE(sld_student.REPORT_DATE,'YYYYMMDD')) || LPAD(EXTRACT(MONTH FROM ctc.CLOSE_DATE),2,'0') || '28','YYYYMMDD')) AS COLLECTION_TYPE_CODE,
    TO_DATE(sld_student.REPORT_DATE,'YYYYMMDD') as OPEN_DATE,
	TO_DATE(EXTRACT(YEAR from TO_DATE(sld_student.REPORT_DATE,'YYYYMMDD')) || '1116', 'YYYYMMDD') as CLOSE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM STUDENT sld_student
where REPORT_DATE > 20110929 AND REPORT_DATE < 20140801 GROUP BY REPORT_DATE;
