UPDATE DISTRICT_MASTER
SET DIST_AREA_CODE = '00'
WHERE DIST_AREA_CODE = ' ';

UPDATE SCHOOL_MASTER
SET SCHOOL_ORGANIZATION_CODE = '010'
WHERE SCHOOL_ORGANIZATION_CODE = ' ';

UPDATE SCHOOL_MASTER
SET FACILITY_TYPE_CODE = '00'
WHERE FACILITY_TYPE_CODE = ' ';