--UPDATE THE DATES LISTED "CHANGEME" to the current date

ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF6';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE SCHOOL_FUNDING_GROUP_CODE
(
    SCHOOL_FUNDING_GROUP_CODE           VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(30)                         NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    LEGACY_CODE                 VARCHAR(10),
    DISPLAY_ORDER               NUMERIC   DEFAULT 1                 NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(32)                         NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(32)                         NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_FUNDING_GROUP_CODE_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_CODE)
);

INSERT INTO SCHOOL_FUNDING_GROUP_CODE (LEGACY_CODE, SCHOOL_FUNDING_GROUP_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('01', 'GROUP1', 'Group 1', 'Group 1 Funding Group', 1,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SCHOOL_FUNDING_GROUP_CODE (LEGACY_CODE, SCHOOL_FUNDING_GROUP_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('02', 'GROUP2', 'Group 2', 'Group 2 Funding Group', 2,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SCHOOL_FUNDING_GROUP_CODE (LEGACY_CODE, SCHOOL_FUNDING_GROUP_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('03', 'GROUP3', 'Group 3', 'Group 3 Funding Group', 3,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SCHOOL_FUNDING_GROUP_CODE (LEGACY_CODE, SCHOOL_FUNDING_GROUP_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('04', 'GROUP4', 'Group 4', 'Group 4 Funding Group', 4,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SCHOOL_FUNDING_GROUP_CODE (LEGACY_CODE, SCHOOL_FUNDING_GROUP_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('05', 'GROUP5', 'Group 5', 'Group 5 Funding Group', 5,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2021-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SCHOOL_FUNDING_GROUP_CODE (LEGACY_CODE, SCHOOL_FUNDING_GROUP_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('06', 'GROUP6', 'Group 6', 'Group 6 Funding Group', 6,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2021-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SCHOOL_FUNDING_GROUP_CODE (LEGACY_CODE, SCHOOL_FUNDING_GROUP_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('07', 'GROUP7', 'Group 7', 'Group 7 Funding Group', 7,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2021-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/MVILLENE',
        to_date('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

CREATE TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP
(
    SCHOOL_FUNDING_GROUP_ID             VARCHAR(255) NOT NULL,
    SCHOOL_ID                           VARCHAR(255) NOT NULL,
    SCHOOL_GRADE_CODE                   VARCHAR(10) NOT NULL,
    SCHOOL_FUNDING_GROUP_CODE           VARCHAR(10) NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_FUNDING_GROUP_ID_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_ID)
);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'KH') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'KF') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '01') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '02') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '03') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '04') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '05') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '06') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '07') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'EU') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '08') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '09') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '10') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'SU') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '11') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '11'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '12') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SLD_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SLD_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '11'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);
