CREATE TABLE DISTRICT
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as DISTRICT_ID,
    TRIM(dist_mast.DISTNO) as DISTRICT_NUMBER,
    CONCAT(TRIM(dist_mast.FAX_AREA),TRIM(dist_mast.FAX_NUMBER)) as FAX_NUMBER,
    CONCAT(TRIM(dist_mast.PHONE_AREA),TRIM(dist_mast.PHONE_NUMBER)) as PHONE_NUMBER,
    TRIM(dist_mast.E_MAIL_ID) as EMAIL,
    TRIM(dist_mast.WEB_ADDRESS) as WEBSITE,
    TRIM(dist_mast.DISTRICT_NAME) as DISTRICT_NAME,
    (SELECT dist_reg.DISTRICT_REGION_CODE from DISTRICT_REGION_CODE dist_reg where TRIM(dist_mast.DIST_AREA_CODE) = dist_reg.LEGACY_CODE) as DISTRICT_REGION_CODE,
    'ACTIVE' as STATUS,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM DISTRICT_MASTER dist_mast;

CREATE TABLE DISTRICT_HISTORY
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as DISTRICT_HISTORY_ID,
    dist.*
FROM DISTRICT dist;

CREATE TABLE INDEPENDENT_AUTHORITY
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as INDEPENDENT_AUTHORITY_ID,
    TRIM(auth_mast.AUTH_NUMBER) as authority_number,
    TRIM(auth_mast.FAX_NUMBER) as FAX_NUMBER,
    TRIM(auth_mast.PHONE_NUMBER) as PHONE_NUMBER,
    TRIM(auth_mast.E_MAIL_ID) as EMAIL,
    TRIM(auth_mast.SCHOOL_AUTHORITY_NAME) as DISPLAY_NAME,
    (SELECT auth_type.AUTHORITY_TYPE_CODE from AUTHORITY_TYPE_CODE auth_type where TRIM(auth_mast.AUTHORITY_TYPE) = SUBSTR(auth_type.AUTHORITY_TYPE_CODE, 0, 1)) as AUTHORITY_TYPE_CODE,
    auth_mast.DATE_OPENED as OPENED_DATE,
    auth_mast.DATE_CLOSED as CLOSED_DATE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM AUTHORITY_MASTER auth_mast;

CREATE TABLE INDEPENDENT_AUTHORITY_HISTORY
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as INDEPENDENT_AUTHORITY_HISTORY_ID,
    auth.*
FROM INDEPENDENT_AUTHORITY auth;

CREATE TABLE SCHOOL
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_ID,
    (SELECT dist.DISTRICT_ID from DISTRICT dist WHERE schl_mast.DISTNO = dist.DISTRICT_NUMBER) as DISTRICT_ID,
    (SELECT auth.INDEPENDENT_AUTHORITY_ID from INDEPENDENT_AUTHORITY auth WHERE schl_mast.AUTH_NUMBER = auth.AUTHORITY_NUMBER) as INDEPENDENT_AUTHORITY_ID,
    TRIM(schl_mast.SCHLNO) as SCHOOL_NUMBER,
    TRIM(schl_mast.SC_FAX_NUMBER) as FAX_NUMBER,
    TRIM(schl_mast.SC_PHONE_NUMBER) as PHONE_NUMBER,
    TRIM(schl_mast.SC_E_MAIL_ID) as EMAIL,
    (CAST(NULL as VARCHAR2(100))) as WEBSITE,
    TRIM(schl_mast.SCHOOL_NAME) as DISPLAY_NAME,
    (SELECT schl_org.SCHOOL_ORGANIZATION_CODE from SCHOOL_ORGANIZATION_CODE schl_org where TRIM(schl_mast.SCHOOL_ORGANIZATION_CODE) = schl_org.LEGACY_CODE) as SCHOOL_ORGANIZATION_CODE,
    (SELECT schl_cat.SCHOOL_CATEGORY_CODE from SCHOOL_CATEGORY_CODE schl_cat where TRIM(schl_mast.SCHOOL_CATEGORY_CODE) = schl_cat.LEGACY_CODE) as SCHOOL_CATEGORY_CODE,
    (SELECT fac_type.FACILITY_TYPE_CODE from FACILITY_TYPE_CODE fac_type where TRIM(schl_mast.FACILITY_TYPE_CODE) = fac_type.LEGACY_CODE) as FACILITY_TYPE_CODE,
    schl_mast.DATE_OPENED as OPENED_DATE,
    schl_mast.DATE_CLOSED as CLOSED_DATE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast;

CREATE TABLE SCHOOL_HISTORY
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_HISTORY_ID,
    schl.*
FROM SCHOOL schl;

CREATE TABLE NOTE
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NOTE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (CAST(NULL as VARCHAR2(100))) as DISTRICT_ID,
    (CAST(NULL as VARCHAR2(100))) as INDEPENDENT_AUTHORITY_ID,
    TRIM(schl_mast."COMMENT") as CONTENT,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast."COMMENT") != ' '
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NOTE_ID,
    (CAST(NULL as VARCHAR2(100))) as SCHOOL_ID,
    (SELECT dist.DISTRICT_ID from DISTRICT dist WHERE dist_mast.DISTNO = dist.DISTRICT_NUMBER) as DISTRICT_ID,
    (CAST(NULL as VARCHAR2(100))) as INDEPENDENT_AUTHORITY_ID,
    TRIM(dist_mast.NOTES) as CONTENT,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM DISTRICT_MASTER dist_mast
WHERE TRIM(dist_mast.NOTES) != ' ';

CREATE TABLE SCHOOL_GRADE
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'KINDHALF' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_KH_IND) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'KINDFULL' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_KF_IND) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE01' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_01_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE02' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_02_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE03' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_03_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE04' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_04_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE05' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_05_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE06' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_06_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE07' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_07_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE08' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_08_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE09' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_09_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE10' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_10_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE11' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_11_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADE12' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_12_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'ELEMUNGR' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_EU_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'SECUNGR' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_SU_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'HOMESCHL' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_HS_IND ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_GRADE_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'GRADADULT' as SCHOOL_GRADE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.GRADE_GA_IND ) = 'Y';

CREATE TABLE NEIGHBOURHOOD_LEARNING
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NEIGHBOURHOOD_LEARNING_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'EARLYLEARN' as NEIGHBOURHOOD_LEARNING_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.NLC_EARLY_LEARNING_FLAG) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NEIGHBOURHOOD_LEARNING_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'AFTERSCHL' as NEIGHBOURHOOD_LEARNING_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.NLC_AFTER_SCHOOL_PROGRAM_FLAG ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NEIGHBOURHOOD_LEARNING_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'CONTINEDUC' as NEIGHBOURHOOD_LEARNING_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.NLC_CONTINUING_ED_FLAG ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NEIGHBOURHOOD_LEARNING_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'SENIORS' as NEIGHBOURHOOD_LEARNING_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.NLC_SENIORS_FLAG ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NEIGHBOURHOOD_LEARNING_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'SPORTRECR' as NEIGHBOURHOOD_LEARNING_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.NLC_SPORT_AND_REC_FLAG ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NEIGHBOURHOOD_LEARNING_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'COMMUNITY' as NEIGHBOURHOOD_LEARNING_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.NLC_COMMUNITY_USE_FLAG ) = 'Y'
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as NEIGHBOURHOOD_LEARNING_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    'INTEGRSERV' as NEIGHBOURHOOD_LEARNING_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.NLC_INTEGRATED_SERVICES_FLAG ) = 'Y';

----------------------------------------------------------------------------------------------

CREATE TABLE ADDRESS
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as ADDRESS_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (CAST(NULL as VARCHAR2(100))) as DISTRICT_ID,
    (CAST(NULL as VARCHAR2(100))) as INDEPENDENT_AUTHORITY_ID,
    TRIM(schl_mast.SC_ADDRESS_LINE_1) as ADDRESS_LINE_1,
    TRIM(schl_mast.SC_ADDRESS_LINE_2) as ADDRESS_LINE_2,
    TRIM(schl_mast.SC_CITY) as CITY,
    (SELECT prov.PROVINCE_CODE FROM PROVINCE_CODE prov where TRIM(schl_mast.SC_PROVINCE_CODE) = prov.LEGACY_CODE) as PROVINCE_CODE,
    TRIM(schl_mast.SC_POSTAL_CODE) as POSTAL_CODE,
    'MAILING' as ADDRESS_TYPE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.SC_ADDRESS_LINE_1) != ' '
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as ADDRESS_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE schl_mast.SCHLNO = schl.SCHOOL_NUMBER AND schl_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (CAST(NULL as VARCHAR2(100))) as DISTRICT_ID,
    (CAST(NULL as VARCHAR2(100))) as INDEPENDENT_AUTHORITY_ID,
    TRIM(schl_mast.PHYS_ADDRESS_LINE_1) as ADDRESS_LINE_1,
    TRIM(schl_mast.PHYS_ADDRESS_LINE_2) as ADDRESS_LINE_2,
    TRIM(schl_mast.PHYS_CITY) as CITY,
    (SELECT prov.PROVINCE_CODE FROM PROVINCE_CODE prov where TRIM(schl_mast.PHYS_PROVINCE_CODE) = prov.LEGACY_CODE) as PROVINCE_CODE,
    TRIM(schl_mast.PHYS_POSTAL_CODE) as POSTAL_CODE,
    'PHYSICAL' as ADDRESS_TYPE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM SCHOOL_MASTER schl_mast
WHERE TRIM(schl_mast.PHYS_ADDRESS_LINE_1) != ' '
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as ADDRESS_ID,
    (CAST(NULL as VARCHAR2(100))) as SCHOOL_ID,
    (SELECT dist.DISTRICT_ID from DISTRICT dist WHERE dist_mast.DISTNO = dist.DISTRICT_NUMBER) as DISTRICT_ID,
    (CAST(NULL as VARCHAR2(100))) as INDEPENDENT_AUTHORITY_ID,
    TRIM(dist_mast.MAIL_ADDRESS_LINE_1) as ADDRESS_LINE_1,
    TRIM(dist_mast.MAIL_ADDRESS_LINE_2) as ADDRESS_LINE_2,
    TRIM(dist_mast.MAIL_CITY) as CITY,
    TRIM(dist_mast.MAIL_PROVINCE_CODE) as PROVINCE_CODE,
    TRIM(dist_mast.MAIL_POSTAL_CODE) as POSTAL_CODE,
    'MAILING' as ADDRESS_TYPE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM DISTRICT_MASTER dist_mast
WHERE TRIM(dist_mast.MAIL_ADDRESS_LINE_1) != ' '
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as ADDRESS_ID,
    (CAST(NULL as VARCHAR2(100))) as SCHOOL_ID,
    (SELECT dist.DISTRICT_ID from DISTRICT dist WHERE dist_mast.DISTNO = dist.DISTRICT_NUMBER) as DISTRICT_ID,
    (CAST(NULL as VARCHAR2(100))) as INDEPENDENT_AUTHORITY_ID,
    TRIM(dist_mast.PHYS_ADDRESS_LINE_1) as ADDRESS_LINE_1,
    TRIM(dist_mast.PHYS_ADDRESS_LINE_2) as ADDRESS_LINE_2,
    TRIM(dist_mast.PHYS_CITY) as CITY,
    TRIM(dist_mast.PHYS_PROVINCE_CODE) as PROVINCE_CODE,
    TRIM(dist_mast.PHYS_POSTAL_CODE) as POSTAL_CODE,
    'PHYSICAL' as ADDRESS_TYPE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM DISTRICT_MASTER dist_mast
WHERE TRIM(dist_mast.PHYS_ADDRESS_LINE_1) != ' '
UNION
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as ADDRESS_ID,
    (CAST(NULL as VARCHAR2(100))) as SCHOOL_ID,
    (CAST(NULL as VARCHAR2(100))) as DISTRICT_ID,
    (SELECT auth.INDEPENDENT_AUTHORITY_ID from INDEPENDENT_AUTHORITY auth WHERE auth_mast.AUTH_NUMBER = auth.AUTHORITY_NUMBER) as INDEPENDENT_AUTHORITY_ID,
    TRIM(auth_mast.ADDRESS_LINE_1) as ADDRESS_LINE_1,
    TRIM(auth_mast.ADDRESS_LINE_2) as ADDRESS_LINE_2,
    TRIM(auth_mast.CITY) as CITY,
    (SELECT prov.PROVINCE_CODE FROM PROVINCE_CODE prov where TRIM(auth_mast.PROVINCE_CODE) = prov.LEGACY_CODE) as PROVINCE_CODE,
    TRIM(auth_mast.POSTAL_CODE) as POSTAL_CODE,
    'MAILING' as ADDRESS_TYPE_CODE,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as UPDATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER
FROM AUTHORITY_MASTER auth_mast
WHERE TRIM(auth_mast.ADDRESS_LINE_1) != ' ';

CREATE TABLE ADDRESS_HISTORY
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as ADDRESS_HISTORY_ID,
    addr.*
FROM ADDRESS addr;