CREATE TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP
(
    SCHOOL_FUNDING_GROUP_ID             VARCHAR(255) NOT NULL,
    SCHOOL_ID                           VARCHAR(255) NOT NULL,
    SCHOOL_GRADE_CODE                   VARCHAR(10) NOT NULL,
    SCHOOL_FUNDING_GROUP_CODE           VARCHAR(10) NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_FUNDING_GROUP_ID_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_ID)
);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'KH') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'KF') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '01') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '02') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '03') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '01'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '04') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '05') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '06') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '07') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'EU') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '04'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '08') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '09') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '10') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'SU') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '08'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '11') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '11'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP (SCHOOL_FUNDING_GROUP_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE fund_mast.SCHLNO = schl.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '12') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = fund_mast.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_MASTER fund_mast, SCHOOL schl_table
WHERE fund_mast.FUNDING_GROUP_SUBCODE = '11'
AND fund_mast.SCHLNO = schl_table.SCHOOL_NUMBER AND fund_mast.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID);

CREATE TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT
as
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'KH') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '01'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'KF') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '01'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '01') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '01'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '02') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '01'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '03') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '01'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '04') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '04'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '05') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '04'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '06') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '04'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '07') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '04'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'EU') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '04'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '08') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '08'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '09') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '08'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '10') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '08'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = 'SU') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '08'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');

INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '11') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '11'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');


INSERT INTO INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID, COLLECTION_ID, SCHOOL_ID, SCHOOL_GRADE_CODE, SCHOOL_FUNDING_GROUP_CODE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT
    LOWER(REGEXP_REPLACE(dbms_crypto.randombytes(16), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) as SCHOOL_FUNDING_GROUP_SNAPSHOT_ID,
    (SELECT COLLECTION_ID FROM COLLECTION coll WHERE TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') BETWEEN coll.OPEN_DATE AND coll.CLOSE_DATE) AS COLLECTION_ID,
    (SELECT schl.SCHOOL_ID from SCHOOL schl WHERE sfc.SCHLNO = schl.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl.DISTRICT_ID = dist.DISTRICT_ID)) as SCHOOL_ID,
    (SELECT grade_code_tbl.SCHOOL_GRADE_CODE from SCHOOL_GRADE_CODE grade_code_tbl where grade_code_tbl.LEGACY_CODE = '12') as SCHOOL_GRADE_CODE,
    (SELECT fund_code_tbl.SCHOOL_FUNDING_GROUP_CODE from SCHOOL_FUNDING_GROUP_CODE fund_code_tbl where fund_code_tbl.LEGACY_CODE = sfc.FUNDING_GROUP_CODE) as SCHOOL_FUNDING_GROUP_CODE,
    'SPM_MIGRATION' as CREATE_USER,
    sysdate as CREATE_DATE,
    'SPM_MIGRATION' as UPDATE_USER,
    sysdate as UPDATE_DATE
FROM SCHOOL_FUNDING_CENSUS sfc, SCHOOL schl_table
WHERE sfc.FUNDING_GROUP_SUBCODE = '11'
AND sfc.SCHLNO = schl_table.SCHOOL_NUMBER AND sfc.DISTNO = (SELECT dist.DISTRICT_NUMBER from DISTRICT dist WHERE schl_table.DISTRICT_ID = dist.DISTRICT_ID)
AND TO_DATE(sfc.REPORT_DATE,'YYYYMMDD') < TO_DATE('CHANGEME','YYYYMMDD');
