UPDATE SCHOOL_CATEGORY_CODE
SET
    LEGACY_CODE = '02'
WHERE
    SCHOOL_CATEGORY_CODE = 'INDP_FNS';

UPDATE FACILITY_TYPE_CODE
SET
    LEGACY_CODE = '00'
WHERE
    FACILITY_TYPE_CODE = 'POST_SEC';

UPDATE FACILITY_TYPE_CODE
SET
    LEGACY_CODE = '10'
WHERE
    FACILITY_TYPE_CODE = 'JUSTB4PRO';

UPDATE DISTRICT_REGION_CODE
SET
    LEGACY_CODE = '00'
WHERE
    DISTRICT_REGION_CODE = 'PSI';

UPDATE DISTRICT_REGION_CODE
SET
    LEGACY_CODE = '00'
WHERE
    DISTRICT_REGION_CODE = 'YUKON';