CREATE TABLE INSTITUTE_SAGA
(
    SAGA_ID            UUID                                NOT NULL,
    SAGA_NAME          VARCHAR(50)                         NOT NULL,
    SAGA_STATE         VARCHAR(100)                        NOT NULL,
    PAYLOAD            VARCHAR                             NOT NULL,
    RETRY_COUNT        INTEGER,
    STATUS             VARCHAR(20)                         NOT NULL,
    SAGA_COMPENSATED   BOOLEAN                             NOT NULL,
    EMAIL_ID           VARCHAR(255),
    SCHOOL_ID          UUID,
    CREATE_USER        VARCHAR(32)                         NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER        VARCHAR(32)                         NOT NULL,
    UPDATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT INSTITUTE_SAGA_PK PRIMARY KEY (SAGA_ID)
);

CREATE INDEX INSTITUTE_SAGA_STATUS_IDX ON INSTITUTE_SAGA (STATUS);
CREATE INDEX INSTITUTE_SAGA_EMAIL_ID_IDX ON INSTITUTE_SAGA (EMAIL_ID);
CREATE INDEX INSTITUTE_SAGA_SCHOOL_ID_IDX ON INSTITUTE_SAGA (SCHOOL_ID);

CREATE TABLE INSTITUTE_SAGA_EVENT_STATES
(
    SAGA_EVENT_ID       UUID                                NOT NULL,
    SAGA_ID             UUID                                NOT NULL,
    SAGA_EVENT_STATE    VARCHAR(100)                        NOT NULL,
    SAGA_EVENT_OUTCOME  VARCHAR(100)                        NOT NULL,
    SAGA_STEP_NUMBER    INTEGER                             NOT NULL,
    SAGA_EVENT_RESPONSE VARCHAR                             NOT NULL,
    CREATE_USER         VARCHAR(32)                         NOT NULL,
    CREATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER         VARCHAR(32)                         NOT NULL,
    UPDATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT INSTITUTE_SAGA_EVENT_STATES_PK PRIMARY KEY (SAGA_EVENT_ID)
);

ALTER TABLE INSTITUTE_SAGA_EVENT_STATES
    ADD CONSTRAINT INSTITUTE_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES INSTITUTE_SAGA (SAGA_ID);
CREATE INDEX INSTITUTE_SAGA_EVENT_STATES_SID_SES_SEO_SSN_IDX ON INSTITUTE_SAGA_EVENT_STATES (SAGA_ID, SAGA_EVENT_STATE, SAGA_EVENT_OUTCOME, SAGA_STEP_NUMBER);
