UPDATE SCHOOL_CATEGORY_CODE SET DESCRIPTION = 'Offshore School' WHERE SCHOOL_CATEGORY_CODE = 'OFFSHORE';
UPDATE SCHOOL_CATEGORY_CODE SET DESCRIPTION = 'Early Learning School' WHERE SCHOOL_CATEGORY_CODE = 'EAR_LEARN';
