UPDATE SCHOOL
SET SCHOOL_CATEGORY_CODE = 'INDEPEND'
WHERE SCHOOL_CATEGORY_CODE = 'SPEC_RPRT';

DELETE FROM SCHOOL_CATEGORY_CODE WHERE SCHOOL_CATEGORY_CODE='SPEC_RPRT';

INSERT INTO SCHOOL_ORGANIZATION_CODE (SCHOOL_ORGANIZATION_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                  DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                  CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('SPEC_RPRT', 'Special Reporting', 'Special Reporting School', NULL, 10,
        TO_DATE('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/TRERICHA',
        TO_DATE('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/TRERICHA',
        TO_DATE('2019-12-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

UPDATE SCHOOL
SET SCHOOL_ORGANIZATION_CODE = 'SPEC_RPRT'
WHERE DISTRICT_ID = (SELECT DISTRICT_ID FROM DISTRICT WHERE DISTRICT_NUMBER = '091')
  AND SCHOOL_NUMBER = '96531';

UPDATE SCHOOL
SET SCHOOL_ORGANIZATION_CODE = 'SPEC_RPRT'
WHERE DISTRICT_ID = (SELECT DISTRICT_ID FROM DISTRICT WHERE DISTRICT_NUMBER = '091')
  AND SCHOOL_NUMBER = '96532';

UPDATE SCHOOL
SET SCHOOL_ORGANIZATION_CODE = 'SPEC_RPRT'
WHERE DISTRICT_ID = (SELECT DISTRICT_ID FROM DISTRICT WHERE DISTRICT_NUMBER = '060')
  AND SCHOOL_NUMBER = '96658';

UPDATE SCHOOL
SET SCHOOL_ORGANIZATION_CODE = 'SPEC_RPRT'
WHERE DISTRICT_ID = (SELECT DISTRICT_ID FROM DISTRICT WHERE DISTRICT_NUMBER = '060')
  AND SCHOOL_NUMBER =  '96677';

UPDATE SCHOOL
SET SCHOOL_ORGANIZATION_CODE = 'SPEC_RPRT'
WHERE DISTRICT_ID = (SELECT DISTRICT_ID FROM DISTRICT WHERE DISTRICT_NUMBER = '091')
  AND SCHOOL_NUMBER = '96415';