ALTER TABLE AUTHORITY_CONTACT_TYPE_CODE ADD COLUMN PUBLICLY_AVAIL BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE DISTRICT_CONTACT_TYPE_CODE ADD COLUMN PUBLICLY_AVAIL BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE SCHOOL_CONTACT_TYPE_CODE ADD COLUMN PUBLICLY_AVAIL BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE DISTRICT_CONTACT_TYPE_CODE SET PUBLICLY_AVAIL=FALSE WHERE DISTRICT_CONTACT_TYPE_CODE='1701';

ALTER TABLE DISTRICT_CONTACT_TYPE_CODE ALTER COLUMN PUBLICLY_AVAIL DROP DEFAULT;
ALTER TABLE AUTHORITY_CONTACT_TYPE_CODE ALTER COLUMN PUBLICLY_AVAIL DROP DEFAULT;
ALTER TABLE SCHOOL_CONTACT_TYPE_CODE ALTER COLUMN PUBLICLY_AVAIL DROP DEFAULT;
