DELETE FROM SCHOOL_GRADE
WHERE SCHOOL_GRADE_CODE = 'HOMESCHL';

DELETE FROM SCHOOL_GRADE
WHERE SCHOOL_GRADE_CODE = 'GRADADULT';

DELETE FROM SCHOOL_GRADE_CODE
WHERE SCHOOL_GRADE_CODE = 'HOMESCHL';

DELETE FROM SCHOOL_GRADE_CODE
WHERE SCHOOL_GRADE_CODE = 'GRADADULT';
