ALTER TABLE AUTHORITY_ADDRESS_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE AUTHORITY_ADDRESS_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_ADDRESS_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_ADDRESS_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_ADDRESS_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_ADDRESS_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);
