ALTER TABLE SCHOOL
    ALTER COLUMN CREATE_USER TYPE VARCHAR(255);

ALTER TABLE SCHOOL
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(255);

ALTER TABLE SCHOOL_CONTACT
    ALTER COLUMN CREATE_USER TYPE VARCHAR(255);

ALTER TABLE SCHOOL_CONTACT
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(255);

ALTER TABLE SCHOOL_MOVE
    ALTER COLUMN CREATE_USER TYPE VARCHAR(255);

ALTER TABLE SCHOOL_MOVE
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(255);

ALTER TABLE SCHOOL_HISTORY
    ALTER COLUMN CREATE_USER TYPE VARCHAR(255);

ALTER TABLE SCHOOL_HISTORY
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(255);

ALTER TABLE DISTRICT
    ALTER COLUMN CREATE_USER TYPE VARCHAR(255);

ALTER TABLE DISTRICT
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(255);

ALTER TABLE DISTRICT_CONTACT
    ALTER COLUMN CREATE_USER TYPE VARCHAR(255);

ALTER TABLE DISTRICT_CONTACT
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(255);

ALTER TABLE DISTRICT_HISTORY
    ALTER COLUMN CREATE_USER TYPE VARCHAR(255);

ALTER TABLE DISTRICT_HISTORY
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(255);

