ALTER TABLE INDEPENDENT_AUTHORITY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE INDEPENDENT_AUTHORITY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE INDEPENDENT_AUTHORITY_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE INDEPENDENT_AUTHORITY_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE AUTHORITY_ADDRESS
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE AUTHORITY_ADDRESS
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE AUTHORITY_CONTACT
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE AUTHORITY_CONTACT
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE AUTHORITY_CONTACT
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE AUTHORITY_CONTACT
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_ADDRESS
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_ADDRESS
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_CONTACT
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE DISTRICT_CONTACT
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE NEIGHBORHOOD_LEARNING
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE NEIGHBORHOOD_LEARNING
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE NEIGHBORHOOD_LEARNING_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE NEIGHBORHOOD_LEARNING_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE NOTE
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE NOTE
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_ADDRESS
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_ADDRESS
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_CONTACT
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_CONTACT
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_GRADE
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_GRADE
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_GRADE_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_GRADE_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_MOVE
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_MOVE
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_HISTORY
ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SCHOOL_HISTORY
ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);


