ALTER TABLE SCHOOL_CONTACT_TYPE_CODE ADD COLUMN IND_ONLY BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE SCHOOL_CONTACT_TYPE_CODE ADD COLUMN OFFSHORE_ONLY BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE AUTHORITY_CONTACT_TYPE_CODE ADD COLUMN IND_ONLY BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE AUTHORITY_CONTACT_TYPE_CODE ADD COLUMN OFFSHORE_ONLY BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE SCHOOL_CONTACT_TYPE_CODE ALTER COLUMN IND_ONLY DROP DEFAULT;
ALTER TABLE SCHOOL_CONTACT_TYPE_CODE ALTER COLUMN OFFSHORE_ONLY DROP DEFAULT;
ALTER TABLE AUTHORITY_CONTACT_TYPE_CODE ALTER COLUMN IND_ONLY DROP DEFAULT;
ALTER TABLE AUTHORITY_CONTACT_TYPE_CODE ALTER COLUMN OFFSHORE_ONLY DROP DEFAULT;

UPDATE SCHOOL_CONTACT_TYPE_CODE SET DISPLAY_ORDER = 20 WHERE SCHOOL_CONTACT_TYPE_CODE = 'VPRINCIPAL';

INSERT INTO SCHOOL_CONTACT_TYPE_CODE (SCHOOL_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                      DISPLAY_ORDER, PUBLICLY_AVAIL, IND_ONLY, OFFSHORE_ONLY, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                      CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('SAFE_COORD', 'Safe Schools Coordinator', 'Safe Schools Coordinator', null, 40, false, true, false,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP, 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP);

INSERT INTO SCHOOL_CONTACT_TYPE_CODE (SCHOOL_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                      DISPLAY_ORDER, PUBLICLY_AVAIL, IND_ONLY, OFFSHORE_ONLY, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                      CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('HEAD_SCH', 'Head of School', 'Head of School', null, 30, true, true, false,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP, 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP);

INSERT INTO SCHOOL_CONTACT_TYPE_CODE (SCHOOL_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                      DISPLAY_ORDER, PUBLICLY_AVAIL, IND_ONLY, OFFSHORE_ONLY, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                      CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('OFFSHORREP', 'Offshore School Representative', 'Offshore School Representative', null, 50, true, false, true,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP, 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP);

INSERT INTO AUTHORITY_CONTACT_TYPE_CODE (AUTHORITY_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                      DISPLAY_ORDER, PUBLICLY_AVAIL, IND_ONLY, OFFSHORE_ONLY, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                      CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('DIRECTOR', 'Director/Board Chair', 'Director/Board Chair', null, 30, true, true, false,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP, 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP);

INSERT INTO AUTHORITY_CONTACT_TYPE_CODE (AUTHORITY_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                      DISPLAY_ORDER, PUBLICLY_AVAIL, IND_ONLY, OFFSHORE_ONLY, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                      CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('OWNER', 'Owner/Operator', 'Owner/Operator', null, 20, true, false, true,
        to_date('2020-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP, 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP);

