ALTER TABLE SCHOOL_ADDRESS_HISTORY ADD COLUMN SCHOOL_HISTORY_ID UUID;

UPDATE SCHOOL_ADDRESS_HISTORY addr
SET SCHOOL_HISTORY_ID=subquery.SCHOOL_HISTORY_ID
FROM (SELECT SCHOOL_HISTORY_ID, SCHOOL_ID
      FROM SCHOOL_HISTORY) AS subquery
WHERE addr.SCHOOL_ID=subquery.SCHOOL_ID;

ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN SCHOOL_HISTORY_ID SET NOT NULL;

ALTER TABLE DISTRICT_ADDRESS_HISTORY ADD COLUMN DISTRICT_HISTORY_ID UUID;

UPDATE DISTRICT_ADDRESS_HISTORY addr
SET DISTRICT_HISTORY_ID=subquery.DISTRICT_HISTORY_ID
FROM (SELECT DISTRICT_HISTORY_ID, DISTRICT_ID
      FROM DISTRICT_HISTORY) AS subquery
WHERE addr.DISTRICT_ID=subquery.DISTRICT_ID;

ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN DISTRICT_HISTORY_ID SET NOT NULL;

ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY ADD COLUMN INDEPENDENT_AUTHORITY_HISTORY_ID UUID;

UPDATE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY addr
SET INDEPENDENT_AUTHORITY_HISTORY_ID=subquery.INDEPENDENT_AUTHORITY_HISTORY_ID
FROM (SELECT INDEPENDENT_AUTHORITY_HISTORY_ID, INDEPENDENT_AUTHORITY_ID
      FROM INDEPENDENT_AUTHORITY_HISTORY) AS subquery
WHERE addr.INDEPENDENT_AUTHORITY_ID=subquery.INDEPENDENT_AUTHORITY_ID;

ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN INDEPENDENT_AUTHORITY_HISTORY_ID SET NOT NULL;
