/** Expire Facility Codes: EDX-904 **/

UPDATE FACILITY_TYPE_CODE
SET
    EXPIRY_DATE = TO_DATE('2022-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE FACILITY_TYPE_CODE IN ('DIST_CONT', 'ELEC_DELIV');