ALTER TABLE SCHOOL ADD COLUMN VENDOR_CODE VARCHAR(10);

CREATE TABLE VENDOR_CODE
(
    VENDOR_CODE                       VARCHAR(10)             NOT NULL,
    LABEL                             VARCHAR(30) NOT NULL,
    DESCRIPTION                       VARCHAR(255) NOT NULL,
    DISPLAY_ORDER                     NUMERIC DEFAULT 1       NOT NULL,
    EFFECTIVE_DATE                    TIMESTAMP               NOT NULL,
    EXPIRY_DATE                       TIMESTAMP               NOT NULL,
    CREATE_USER                       VARCHAR(32)             NOT NULL,
    CREATE_DATE                       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                       VARCHAR(32)             NOT NULL,
    UPDATE_DATE                       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO VENDOR_CODE (VENDOR_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES 
('MYED', 'My Education', 'Vendor code for My Education system', 1, CURRENT_TIMESTAMP, '9999-12-31 00:00:00.000', 'CMCDERMI', CURRENT_TIMESTAMP, 'CMCDERMI', CURRENT_TIMESTAMP),
('OTHER', 'Other Vendor', 'Vendor code for other systems', 2, CURRENT_TIMESTAMP, '9999-12-31 00:00:00.000', 'CMCDERMI', CURRENT_TIMESTAMP, 'CMCDERMI', CURRENT_TIMESTAMP);
