UPDATE DISTRICT_CONTACT_TYPE_CODE
SET
    EXPIRY_DATE = TO_DATE('2023-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    UPDATE_USER = 'IDIR/JOHCOX',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE DISTRICT_CONTACT_TYPE_CODE = 'DIST_LEARN';

INSERT INTO DISTRICT_CONTACT_TYPE_CODE (DISTRICT_CONTACT_TYPE_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                        DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                        CREATE_DATE, UPDATE_USER, UPDATE_DATE, PUBLICLY_AVAIL)
VALUES ('OL_LEARN', 'Online Learning Contact', 'Online Learning Contact', 'OL', 17,
        to_date('2023-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP, 'IDIR/JOHCOX',
        CURRENT_TIMESTAMP, TRUE);