ALTER TABLE SCHOOL_CONTACT
ALTER COLUMN FIRST_NAME DROP NOT NULL;

ALTER TABLE DISTRICT_CONTACT
    ALTER COLUMN FIRST_NAME DROP NOT NULL;

ALTER TABLE AUTHORITY_CONTACT
    ALTER COLUMN FIRST_NAME DROP NOT NULL;