/** Apply sort order to all Grades Offered dropdowns: EDX-881 **/

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 1,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'KINDHALF';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 2,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'KINDFULL';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 3,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE01';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 4,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE02';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 5,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE03';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 6,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE04';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 7,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE05';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 8,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE06';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 9,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE07';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 10,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'ELEMUNGR';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 11,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE08';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 12,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE09';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 13,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE10';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 14,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE11';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 15,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'GRADE12';

UPDATE SCHOOL_GRADE_CODE
SET
    DISPLAY_ORDER = 16,
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = TO_DATE(CURRENT_TIMESTAMP::text, 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHOOL_GRADE_CODE = 'SECUNGR';