UPDATE DISTRICT_CONTACT_TYPE_CODE
SET
    EXPIRY_DATE = TO_DATE('2023-07-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE DISTRICT_CONTACT_TYPE_CODE = 'PLANNING';