UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 1
WHERE
    SCHOOL_CATEGORY_CODE = 'PUBLIC';

UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 2
WHERE
    SCHOOL_CATEGORY_CODE = 'INDEPEND';

UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 3
WHERE
    SCHOOL_CATEGORY_CODE = 'INDP_FNS';

UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 4
WHERE
    SCHOOL_CATEGORY_CODE = 'FED_BAND';

UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 5
WHERE
    SCHOOL_CATEGORY_CODE = 'OFFSHORE';

UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 6
WHERE
    SCHOOL_CATEGORY_CODE = 'EAR_LEARN';

UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 7
WHERE
    SCHOOL_CATEGORY_CODE = 'YUKON';

UPDATE SCHOOL_CATEGORY_CODE
SET
    DISPLAY_ORDER = 8
WHERE
    SCHOOL_CATEGORY_CODE = 'POST_SEC';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 1
WHERE
    FACILITY_TYPE_CODE = 'STANDARD';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 2
WHERE
    FACILITY_TYPE_CODE = 'CONT_ED';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 3
WHERE
    FACILITY_TYPE_CODE = 'DIST_LEARN';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 4
WHERE
    FACILITY_TYPE_CODE = 'DISTONLINE';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 5
WHERE
    FACILITY_TYPE_CODE = 'ALT_PROGS';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 6
WHERE
    FACILITY_TYPE_CODE = 'STRONG_CEN';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 7
WHERE
    FACILITY_TYPE_CODE = 'STRONG_OUT';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 8
WHERE
    FACILITY_TYPE_CODE = 'JUSTB4PRO';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 9
WHERE
        FACILITY_TYPE_CODE = 'SHORT_PRP';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 10
WHERE
        FACILITY_TYPE_CODE = 'LONG_PRP';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 11
WHERE
        FACILITY_TYPE_CODE = 'SUMMER';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 12
WHERE
        FACILITY_TYPE_CODE = 'YOUTH';

UPDATE FACILITY_TYPE_CODE
SET
    DISPLAY_ORDER = 13
WHERE
        FACILITY_TYPE_CODE = 'POST_SEC';
