CREATE TABLE DISTRICT_ADDRESS
as
SELECT
    gen_random_uuid() as DISTRICT_ADDRESS_ID,
    addr.DISTRICT_ID as DISTRICT_ID,
    addr.ADDRESS_LINE_1 as ADDRESS_LINE_1,
    addr.ADDRESS_LINE_2 as ADDRESS_LINE_2,
    addr.CITY as CITY,
    addr.POSTAL as POSTAL,
    addr.PROVINCE_CODE as PROVINCE_CODE,
    addr.COUNTRY_CODE as COUNTRY_CODE,
    addr.ADDRESS_TYPE_CODE as ADDRESS_TYPE_CODE,
    addr.CREATE_USER as CREATE_USER,
    addr.CREATE_DATE as CREATE_DATE,
    addr.UPDATE_USER as UPDATE_USER,
    addr.UPDATE_DATE as UPDATE_DATE
FROM ADDRESS addr
WHERE DISTRICT_ID is not null;

ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN DISTRICT_ADDRESS_ID SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN DISTRICT_ID SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN ADDRESS_LINE_1 SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN CITY SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN POSTAL SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN PROVINCE_CODE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN COUNTRY_CODE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN ADDRESS_TYPE_CODE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN CREATE_USER SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN CREATE_DATE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN UPDATE_USER SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS
    ALTER COLUMN UPDATE_DATE SET NOT NULL;

CREATE TABLE DISTRICT_ADDRESS_HISTORY
as
SELECT
    gen_random_uuid() as DISTRICT_ADDRESS_HISTORY_ID,
    addy.*
FROM DISTRICT_ADDRESS addy;

ALTER TABLE DISTRICT_ADDRESS_HISTORY
    DROP COLUMN DISTRICT_ADDRESS_ID;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN DISTRICT_ADDRESS_HISTORY_ID SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN DISTRICT_ID SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN ADDRESS_LINE_1 SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN CITY SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN POSTAL SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN PROVINCE_CODE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN COUNTRY_CODE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN ADDRESS_TYPE_CODE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN CREATE_USER SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN CREATE_DATE SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN UPDATE_USER SET NOT NULL;
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ALTER COLUMN UPDATE_DATE SET NOT NULL;

--District Address & District Address History Foreign Keys
ALTER TABLE DISTRICT_ADDRESS
    ADD CONSTRAINT DISTRICT_ADDRESS_PK PRIMARY KEY (DISTRICT_ADDRESS_ID);
ALTER TABLE DISTRICT_ADDRESS
    ADD CONSTRAINT FK_DISTRICT_ADDRESS_DISTRICT_ID FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT (DISTRICT_ID);
ALTER TABLE DISTRICT_ADDRESS
    ADD CONSTRAINT FK_DISTRICT_ADDRESS_ADDRESS_TYPE_CODE FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES ADDRESS_TYPE_CODE (ADDRESS_TYPE_CODE);
ALTER TABLE DISTRICT_ADDRESS
    ADD CONSTRAINT FK_DISTRICT_ADDRESS_PROVINCE_CODE FOREIGN KEY (PROVINCE_CODE) REFERENCES PROVINCE_CODE (PROVINCE_CODE);
ALTER TABLE DISTRICT_ADDRESS
    ADD CONSTRAINT FK_DISTRICT_ADDRESS_COUNTRY_CODE FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_CODE (COUNTRY_CODE);
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ADD CONSTRAINT DISTRICT_ADDRESS_HISTORY_PK PRIMARY KEY (DISTRICT_ADDRESS_HISTORY_ID);
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ADD CONSTRAINT FK_DISTRICT_ADDRESS_HISTORY_ADDRESS_TYPE_CODE FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES ADDRESS_TYPE_CODE (ADDRESS_TYPE_CODE);
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ADD CONSTRAINT FK_DISTRICT_ADDRESS_HISTORY_PROVINCE_CODE FOREIGN KEY (PROVINCE_CODE) REFERENCES PROVINCE_CODE (PROVINCE_CODE);
ALTER TABLE DISTRICT_ADDRESS_HISTORY
    ADD CONSTRAINT FK_DISTRICT_ADDRESS_HISTORY_COUNTRY_CODE FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_CODE (COUNTRY_CODE);

CREATE TABLE SCHOOL_ADDRESS
as
SELECT
    gen_random_uuid() as SCHOOL_ADDRESS_ID,
    addr.SCHOOL_ID as SCHOOL_ID,
    addr.ADDRESS_LINE_1 as ADDRESS_LINE_1,
    addr.ADDRESS_LINE_2 as ADDRESS_LINE_2,
    addr.CITY as CITY,
    addr.POSTAL as POSTAL,
    addr.PROVINCE_CODE as PROVINCE_CODE,
    addr.COUNTRY_CODE as COUNTRY_CODE,
    addr.ADDRESS_TYPE_CODE as ADDRESS_TYPE_CODE,
    addr.CREATE_USER as CREATE_USER,
    addr.CREATE_DATE as CREATE_DATE,
    addr.UPDATE_USER as UPDATE_USER,
    addr.UPDATE_DATE as UPDATE_DATE
FROM ADDRESS addr
WHERE SCHOOL_ID is not null;

ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN SCHOOL_ADDRESS_ID SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN SCHOOL_ID SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN ADDRESS_LINE_1 SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN CITY SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN POSTAL SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN PROVINCE_CODE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN COUNTRY_CODE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN ADDRESS_TYPE_CODE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN CREATE_USER SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN CREATE_DATE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN UPDATE_USER SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS
    ALTER COLUMN UPDATE_DATE SET NOT NULL;

CREATE TABLE SCHOOL_ADDRESS_HISTORY
as
SELECT
    gen_random_uuid() as SCHOOL_ADDRESS_HISTORY_ID,
    addy.*
FROM SCHOOL_ADDRESS addy;

ALTER TABLE SCHOOL_ADDRESS_HISTORY
    DROP COLUMN SCHOOL_ADDRESS_ID;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN SCHOOL_ADDRESS_HISTORY_ID SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN SCHOOL_ID SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN ADDRESS_LINE_1 SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN CITY SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN POSTAL SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN PROVINCE_CODE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN COUNTRY_CODE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN ADDRESS_TYPE_CODE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN CREATE_USER SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN CREATE_DATE SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN UPDATE_USER SET NOT NULL;
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ALTER COLUMN UPDATE_DATE SET NOT NULL;

--School Address & School Address History Foreign Keys
ALTER TABLE SCHOOL_ADDRESS
    ADD CONSTRAINT SCHOOL_ADDRESS_PK PRIMARY KEY (SCHOOL_ADDRESS_ID);
ALTER TABLE SCHOOL_ADDRESS
    ADD CONSTRAINT FK_SCHOOL_ADDRESS_SCHOOL_ID FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (SCHOOL_ID);
ALTER TABLE SCHOOL_ADDRESS
    ADD CONSTRAINT FK_SCHOOL_ADDRESS_ADDRESS_TYPE_CODE FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES ADDRESS_TYPE_CODE (ADDRESS_TYPE_CODE);
ALTER TABLE SCHOOL_ADDRESS
    ADD CONSTRAINT FK_SCHOOL_ADDRESS_PROVINCE_CODE FOREIGN KEY (PROVINCE_CODE) REFERENCES PROVINCE_CODE (PROVINCE_CODE);
ALTER TABLE SCHOOL_ADDRESS
    ADD CONSTRAINT FK_SCHOOL_ADDRESS_COUNTRY_CODE FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_CODE (COUNTRY_CODE);
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ADD CONSTRAINT SCHOOL_ADDRESS_HISTORY_PK PRIMARY KEY (SCHOOL_ADDRESS_HISTORY_ID);
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ADD CONSTRAINT FK_SCHOOL_ADDRESS_HISTORY_ADDRESS_TYPE_CODE FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES ADDRESS_TYPE_CODE (ADDRESS_TYPE_CODE);
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ADD CONSTRAINT FK_SCHOOL_ADDRESS_HISTORY_PROVINCE_CODE FOREIGN KEY (PROVINCE_CODE) REFERENCES PROVINCE_CODE (PROVINCE_CODE);
ALTER TABLE SCHOOL_ADDRESS_HISTORY
    ADD CONSTRAINT FK_SCHOOL_ADDRESS_HISTORY_COUNTRY_CODE FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_CODE (COUNTRY_CODE);

CREATE TABLE INDEPENDENT_AUTHORITY_ADDRESS
as
SELECT
    gen_random_uuid() as INDEPENDENT_AUTHORITY_ADDRESS_ID,
    addr.INDEPENDENT_AUTHORITY_ID as INDEPENDENT_AUTHORITY_ID,
    addr.ADDRESS_LINE_1 as ADDRESS_LINE_1,
    addr.ADDRESS_LINE_2 as ADDRESS_LINE_2,
    addr.CITY as CITY,
    addr.POSTAL as POSTAL,
    addr.PROVINCE_CODE as PROVINCE_CODE,
    addr.COUNTRY_CODE as COUNTRY_CODE,
    addr.ADDRESS_TYPE_CODE as ADDRESS_TYPE_CODE,
    addr.CREATE_USER as CREATE_USER,
    addr.CREATE_DATE as CREATE_DATE,
    addr.UPDATE_USER as UPDATE_USER,
    addr.UPDATE_DATE as UPDATE_DATE
FROM ADDRESS addr
WHERE INDEPENDENT_AUTHORITY_ID is not null;

ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN INDEPENDENT_AUTHORITY_ADDRESS_ID SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN INDEPENDENT_AUTHORITY_ID SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN ADDRESS_LINE_1 SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN CITY SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN POSTAL SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN PROVINCE_CODE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN COUNTRY_CODE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN ADDRESS_TYPE_CODE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN CREATE_USER SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN CREATE_DATE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN UPDATE_USER SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ALTER COLUMN UPDATE_DATE SET NOT NULL;

CREATE TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
as
SELECT
    gen_random_uuid() as INDEPENDENT_AUTHORITY_ADDRESS_HISTORY_ID,
    addy.*
FROM INDEPENDENT_AUTHORITY_ADDRESS addy;

ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    DROP COLUMN INDEPENDENT_AUTHORITY_ADDRESS_ID;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN INDEPENDENT_AUTHORITY_ADDRESS_HISTORY_ID SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN INDEPENDENT_AUTHORITY_ID SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN ADDRESS_LINE_1 SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN CITY SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN POSTAL SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN PROVINCE_CODE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN COUNTRY_CODE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN ADDRESS_TYPE_CODE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN CREATE_USER SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN CREATE_DATE SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN UPDATE_USER SET NOT NULL;
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ALTER COLUMN UPDATE_DATE SET NOT NULL;

--Authority Address & Authority Address History Foreign Keys
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ADD CONSTRAINT INDEPENDENT_AUTHORITY_ADDRESS_PK PRIMARY KEY (INDEPENDENT_AUTHORITY_ADDRESS_ID);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ADD CONSTRAINT FK_INDEPENDENT_AUTHORITY_ADDRESS_INDEPENDENT_AUTHORITY_ID FOREIGN KEY (INDEPENDENT_AUTHORITY_ID) REFERENCES INDEPENDENT_AUTHORITY (INDEPENDENT_AUTHORITY_ID);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ADD CONSTRAINT FK_INDEPENDENT_AUTHORITY_ADDRESS_ADDRESS_TYPE_CODE FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES ADDRESS_TYPE_CODE (ADDRESS_TYPE_CODE);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ADD CONSTRAINT FK_INDEPENDENT_AUTHORITY_ADDRESS_PROVINCE_CODE FOREIGN KEY (PROVINCE_CODE) REFERENCES PROVINCE_CODE (PROVINCE_CODE);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS
    ADD CONSTRAINT FK_INDEPENDENT_AUTHORITY_ADDRESS_COUNTRY_CODE FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_CODE (COUNTRY_CODE);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ADD CONSTRAINT INDEPENDENT_AUTHORITY_ADDRESS_HISTORY_PK PRIMARY KEY (INDEPENDENT_AUTHORITY_ADDRESS_HISTORY_ID);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ADD CONSTRAINT FK_INDEPENDENT_AUTHORITY_ADDRESS_HISTORY_ADDRESS_TYPE_CODE FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES ADDRESS_TYPE_CODE (ADDRESS_TYPE_CODE);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ADD CONSTRAINT FK_INDEPENDENT_AUTHORITY_ADDRESS_HISTORY_PROVINCE_CODE FOREIGN KEY (PROVINCE_CODE) REFERENCES PROVINCE_CODE (PROVINCE_CODE);
ALTER TABLE INDEPENDENT_AUTHORITY_ADDRESS_HISTORY
    ADD CONSTRAINT FK_INDEPENDENT_AUTHORITY_ADDRESS_HISTORY_COUNTRY_CODE FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY_CODE (COUNTRY_CODE);

DROP TABLE ADDRESS_HISTORY;
DROP TABLE ADDRESS;
