/** EDX-1189: Create New District Region Codes */

INSERT INTO DISTRICT_REGION_CODE (DISTRICT_REGION_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                  DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                  CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('PSI', 'Post Secondary', 'Post Secondary Institution Region', null, 10,
        CURRENT_TIMESTAMP,
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/ASODHI',
        CURRENT_TIMESTAMP, 'IDIR/ASODHI',
        CURRENT_TIMESTAMP);

INSERT INTO DISTRICT_REGION_CODE (DISTRICT_REGION_CODE, LABEL, DESCRIPTION, LEGACY_CODE,
                                  DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                  CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('YUKON', 'Yukon', 'Yukon Region', null, 10,
        CURRENT_TIMESTAMP,
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'IDIR/ASODHI',
        CURRENT_TIMESTAMP, 'IDIR/ASODHI',
        CURRENT_TIMESTAMP);

UPDATE DISTRICT
SET
    DISTRICT_REGION_CODE = 'PSI',
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE DISTRICT_NUMBER = '102';

UPDATE DISTRICT
SET
    DISTRICT_REGION_CODE = 'YUKON',
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE DISTRICT_NUMBER = '098';

UPDATE DISTRICT
SET
    DISTRICT_REGION_CODE = 'OFFSHORE',
    UPDATE_USER = 'IDIR/AVSODHI',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE DISTRICT_NUMBER = '103';