CREATE TABLE SCHOOL_GRADE_HISTORY
(
    SCHOOL_GRADE_HISTORY_ID             UUID NOT NULL,
    SCHOOL_HISTORY_ID                   UUID NOT NULL,
    SCHOOL_GRADE_CODE                   VARCHAR(10) NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_GRADE_HISTORY_ID_PK PRIMARY KEY (SCHOOL_GRADE_HISTORY_ID)
);

CREATE TABLE NEIGHBOURHOOD_LEARNING_HISTORY
(
    NEIGHBOURHOOD_LEARNING_HIST_ID    UUID NOT NULL,
    SCHOOL_HISTORY_ID                   UUID NOT NULL,
    NEIGHBOURHOOD_LEARNING_TYPE_CODE     VARCHAR(10) NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT NEIGHBOURHOOD_LEARN_HIST_ID_PK PRIMARY KEY (NEIGHBOURHOOD_LEARNING_HIST_ID)
);

--School Grade School History Foreign Key
ALTER TABLE SCHOOL_GRADE_HISTORY
    ADD  CONSTRAINT SCHOOL_GRADE_SCHOOL_HISTORY_FK FOREIGN KEY (SCHOOL_HISTORY_ID) REFERENCES SCHOOL_HISTORY (SCHOOL_HISTORY_ID);

--Neighborhood Learning School History Foreign Key
ALTER TABLE NEIGHBOURHOOD_LEARNING_HISTORY
    ADD CONSTRAINT NEIGHBOURHOOD_LEARNING_SH_FK FOREIGN KEY (SCHOOL_HISTORY_ID) REFERENCES SCHOOL_HISTORY (SCHOOL_HISTORY_ID);
