UPDATE SCHOOL_HISTORY
  SET SCHOOL_ORGANIZATION_CODE = 'SPEC_RPRT',
      SCHOOL_REPORTING_REQUIREMENT_CODE = 'NONE'
  FROM DISTRICT,
  (VALUES
    ('091', '96531'),
    ('091', '96532'),
    ('060', '96658'),
    ('060', '96677'),
    ('091', '96415')
  ) AS MINCODE (DISTRICT_NUMBER, SCHOOL_NUMBER)
  WHERE DISTRICT.DISTRICT_ID = (
    SELECT DISTRICT_ID
      FROM DISTRICT
      WHERE DISTRICT_NUMBER = MINCODE.DISTRICT_NUMBER
    )
    AND SCHOOL_HISTORY.SCHOOL_NUMBER = MINCODE.SCHOOL_NUMBER;

